name: mazra3ty_app_admin
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.1.4



dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter

  snippet_coder_utils: ^1.0.13
  iconsax: ^0.0.8
  line_awesome_flutter: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.4
  google_fonts: ^6.1.0
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.1.0
  flutter_otp_text_field: ^1.1.1
  page_transition: ^2.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  quickalert: ^1.0.2
  flutter_easyloading: ^3.0.5
  flutter_riverpod: ^2.1.1
  toggle_switch: ^2.1.0
  font_awesome_flutter: ^10.6.0
  syncfusion_flutter_charts: ^23.1.44
  syncfusion_flutter_core: 23.1.44
  pie_chart: ^5.4.0
  dio: ^5.3.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0







flutter:
  uses-material-design: true
  assets:
    - assets/images/


