name: mazra3ty_app_farmer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


#------------ PACKAGES ---------------
dependencies:
  flutter:
    sdk: flutter


  

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  line_awesome_flutter: ^2.0.0
  google_nav_bar: ^5.0.6
  flutter_native_splash: ^2.3.4
  google_fonts: ^6.1.0
  get: ^4.6.5
  get_storage: ^2.1.1
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_otp_text_field: ^1.1.1
  page_transition: ^2.1.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_charts: ^23.2.4
  fl_chart: ^0.65.0
  percent_indicator: ^4.2.3
  socket_io_client: ^3.0.0-beta.0
  web_socket_channel: ^2.2.0
  
 
  # Utility Packages
  http: ^1.1.2
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Splash Screen
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/logos/logo.png
  image_dark: assets/logos/logo.png
  android_12:
    image: assets/logos/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/logos/logo.png
    icon_background_color_dark: "#272727"







flutter:
  uses-material-design: true
#  ------------ LOCAL ASSETS ------------------------
  assets:
    - assets/images/
    - assets/icons/brands/
    - assets/logos/
    - assets/images/gif/

# ------------ LOCAL Fonts ------------------------
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

